//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoMapper.Analyzers.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RulesResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RulesResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutoMapper.Analyzers.Common.RulesResources", typeof(RulesResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile class must contain maps..
        /// </summary>
        internal static string AMA0001Description {
            get {
                return ResourceManager.GetString("AMA0001Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile &apos;{0}&apos; doesn&apos;t contain any map..
        /// </summary>
        internal static string AMA0001Message {
            get {
                return ResourceManager.GetString("AMA0001Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile doesn&apos;t contain maps..
        /// </summary>
        internal static string AMA0001Title {
            get {
                return ResourceManager.GetString("AMA0001Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties with identical names should not be mapped manually..
        /// </summary>
        internal static string AMA0002Description {
            get {
                return ResourceManager.GetString("AMA0002Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile &apos;{0}&apos; contain map &apos;{1}&apos; with identical properties mapping..
        /// </summary>
        internal static string AMA0002Message {
            get {
                return ResourceManager.GetString("AMA0002Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identical names properties manual mapped..
        /// </summary>
        internal static string AMA0002Title {
            get {
                return ResourceManager.GetString("AMA0002Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Null checking for properties with identical names should be done by NullSubstitute call..
        /// </summary>
        internal static string AMA0003Description {
            get {
                return ResourceManager.GetString("AMA0003Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile &apos;{0}&apos; contain map &apos;{1}&apos; with manual null checking identical source property..
        /// </summary>
        internal static string AMA0003Message {
            get {
                return ResourceManager.GetString("AMA0003Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual checking that source property is null..
        /// </summary>
        internal static string AMA0003Title {
            get {
                return ResourceManager.GetString("AMA0003Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flattening of complex model with naming similar internal properties should be done by `IncludeMember` call..
        /// </summary>
        internal static string AMA0005Description {
            get {
                return ResourceManager.GetString("AMA0005Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile &apos;{0}&apos; contain map &apos;{1}&apos; with manual flattening of internal naming similar complex model..
        /// </summary>
        internal static string AMA0005Message {
            get {
                return ResourceManager.GetString("AMA0005Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual flattening of internal naming similar complex model..
        /// </summary>
        internal static string AMA0005Title {
            get {
                return ResourceManager.GetString("AMA0005Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flattening of naming similar complex model will be done automatically..
        /// </summary>
        internal static string AMA0006Description {
            get {
                return ResourceManager.GetString("AMA0006Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile &apos;{0}&apos; contain map &apos;{1}&apos; with manual flattening of naming similar complex model..
        /// </summary>
        internal static string AMA0006Message {
            get {
                return ResourceManager.GetString("AMA0006Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual flattening of naming similar complex model..
        /// </summary>
        internal static string AMA0006Title {
            get {
                return ResourceManager.GetString("AMA0006Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateMap into Profile should not be covered by try-catch/finally..
        /// </summary>
        internal static string AMA0007Description {
            get {
                return ResourceManager.GetString("AMA0007Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile &apos;{0}&apos; contain map &apos;{1}&apos; covered by {2}..
        /// </summary>
        internal static string AMA0007Message {
            get {
                return ResourceManager.GetString("AMA0007Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cover CreateMap by try-catch/finally..
        /// </summary>
        internal static string AMA0007Title {
            get {
                return ResourceManager.GetString("AMA0007Title", resourceCulture);
            }
        }
    }
}
